title: Dereje Mechal Molla
# description: Welcome to my personal website!
theme: jekyll-theme-time-machine

# custom styles
sass:
  sass_dir: assets/css

# Navigation links
nav:
  - title: "Home"
    url: /
  - title: "About"
    url: /about
  - title: "Publications"
    url: /publication

author: Dereje Mechal Molla

# URL settings
url: "https://derejemm.github.io"   # Replace with your GitHub Pages URL
baseurl: ""                         # Leave empty for user/organization site


# Social links (optional)
github_username: derejemm
linkedin: linkedin.com/in/dereje-mechal-molla-963a6162
twitter_username: dere1223

# Build settings
markdown: kramdown
